title: TeamNexus
description: Android Open Source Project Device-Development
permalink: /post/:year/:month/:day/:title/
paginate: 10
paginate_path: "/blog/:num/"
layout: default
excerpt_separator: <!-- more -->
gems: [ jekyll-paginate ]
